var data = [
{  "name" : "Tom", "subject" : "EN", "score" : 92.0 },
{  "name" : "Tom", "subject" : "AI", "score" : 66.0 },
{  "name" : "Tom", "subject" : "DB", "score" : 52.0 },
{  "name" : "Tom", "subject" : "CH", "score" : 43.0 },
{  "name" : "Sam", "subject" : "CS", "score" : 84.0 },
{  "name" : "Sam", "subject" : "EN", "score" : 93.0 },
{  "name" : "Sam", "subject" : "AI", "score" : 78.0 },
{  "name" : "Sam", "subject" : "DB", "score" : 73.0 },
{  "name" : "Sam", "subject" : "CH", "score" : 91.0 },
{  "name" : "Apple", "subject" : "CS", "score" : 86.0 },
{  "name" : "Apple", "subject" : "EN", "score" : 97.0 },
{  "name" : "Apple", "subject" : "AI", "score" : 85.0 },
{  "name" : "Apple", "subject" : "DB", "score" : 34.0 },
{  "name" : "Mike", "subject" : "CS", "score" : 50.0 },
{  "name" : "Mike", "subject" : "EN", "score" : 44.0 },
{  "name" : "Mike", "subject" : "AI", "score" : 80.0 },
{  "name" : "Mike", "subject" : "DB", "score" : 56.0 },
{  "name" : "Mike", "subject" : "CH", "score" : 88.0 },
{  "name" : "Helle", "subject" : "CS", "score" : 24.0 },
{  "name" : "Helle", "subject" : "EN", "score" : 57.0 },
{  "name" : "Helle", "subject" : "DB", "score" : 49.0 },
{  "name" : "Helle", "subject" : "CH", "score" : 28.0 },
{  "name" : "Billy", "subject" : "CS", "score" : 75.0 },
{  "name" : "Billy", "subject" : "EN", "score" : 91.0 },
{  "name" : "Billy", "subject" : "AI", "score" : 46.0 },
{  "name" : "Billy", "subject" : "DB", "score" : 37.0}
];

db.ch6_agg_1.insert(data);